### PR TITLE
Add -lrt to argos_dumper link libraries

### LINKED ISSUE #204: Issue when compiling the PipeViewer
I have followed the instructions in the readme to build the pipeViewer and encountered a linking error when making. The error is as follows:

```
/home/bscuser/miniconda3/envs/sparta/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../../sparta/libsparta.a(Scheduler.cpp.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/home/bscuser/miniconda3/envs/sparta/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/bscuser/miniconda3/envs/sparta/bin/../x86_64-conda-linux-gnu/sysroot/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [helios/pipeViewer/argos_dumper/CMakeFiles/Argos_dumper.dir/build.make:114: helios/pipeViewer/argos_dumper/Argos_dumper] Error 1
make[1]: *** [CMakeFiles/Makefile2:5418: helios/pipeViewer/argos_dumper/CMakeFiles/Argos_dumper.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Basically, the linking failed for _clock_gettime_. I think that this is related to my linker always getting passed the _-Wl, --as-needed_ flags. I have fixed this and successfully completed compilation/linking by adding _-lrt_ to the _target_link_libraries_ in _map/helios/pipeViewer/argos_dumper/CMakeLists.txt_

### PR DESCRIPTION
**Pull request by bdutro**
Fixes #204

### CODE REVIEW

**Review by knute-sifive — APPROVED** [review]

**Comment by knute-sifive** [comment]
Thanks!

**Comment by timsnyder** [comment]
I think that I already fixed this in #205 I didn't see #204 or I would have closed it in that PR.

**Comment by bdutro** [comment]
Yep, @timsnyder is right.

**Comment by knute-sifive** [comment]
I think `rt` should be part of the `${Sparta_LIB}` variable.  This fails on the Mac.

**Comment by bdutro** [comment]
This was already fixed in PR #205.

**Pull request closed without merging**
