### PR TITLE
Removed automerge/webservies workflows

### PR DESCRIPTION
**Pull request by knute-sifive**
Hey Tim, these files popped up from the latest smithy rendering.  No clue what they're for, but I'm getting slammed with email about them.  Can you approve this PR?

### CODE REVIEW

**Comment by timsnyder** [comment]
Sorry I didn't see the email about this PR.  Why did you close it?  You can remove them like you did but you _should_ be able to prevent conda-smithy from rendering them by adding them to the list of crap you don't want in the `skip_render` list at https://github.com/sparcians/map/blob/edc3b2a2285f6c36b2a5c8311b147649959b6926/conda-forge.yml#L2-L9

I see `.github` in the list there already and it seems to not be working to prevent everything below `.github` from being touched by conda-smithy.  Let me know if you want me to dig into why.  I don't mind and I've submitted PRs to their python before.

**Comment by timsnyder** [comment]
Oh, I looked at the docs for `skip_render` and I guess they only say they support a subset of possible things that can be optional. see https://conda-forge.org/docs/maintainer/conda_forge_yml.html#skip-render

Well, I guess it's because I already tried to address this but it hasn't been merged.  See https://github.com/conda-forge/conda-smithy/pull/1613

**Comment by knute-sifive** [comment]
I decided to merge this PR with the other open one.

**Comment by knute-sifive** [comment]
Appreciate your looking at it and I'll add them to the list of crap I don't want rendered.  😆

**Pull request closed without merging**
