### PR TITLE
Sparta handler for const method

### PR DESCRIPTION
**Pull request by avinabadasgupta**

### CODE REVIEW

**Comment by avinabadasgupta** [comment]
@klingaard , I've put together this PR just for the SpartaHandler const method thing.
So, it supports const methods now.
This is the first part of the issue which you mentioned.
If you want this change, I can merge it in.

**Comment by klingaard** [comment]
Regression looks good with this change.  One test failed, but it's unrelated.  I fixed it and am running regression again just to make sure.

**Comment by avinabadasgupta** [comment]
> Regression looks good with this change. One test failed, but it's unrelated. I fixed it and am running regression again just to make sure.

Sounds good, thanks.

**Comment by avinabadasgupta** [comment]
> Regression at SiFive passed.

Awesome, merging it in.

**Pull request merged**
