### PR TITLE
Cleaned up a lot of documentation, but there's a lot more to go

### PR DESCRIPTION
**Pull request by klingaard**

### CODE REVIEW

**Comment by avinabadasgupta** [comment]
skeleton test is failing.

**Comment by klingaard** [comment]
Ack!  Forgot to commit a file.  Will do so tomorrow.

**Comment by klingaard** [comment]
Ok, updated CMakeList file tester for SkeletalPipeline

**Comment by avinabadasgupta** [comment]
> Ok, updated CMakeList file tester for SkeletalPipeline

Massive effort. Looks great!

**Comment by klingaard** [comment]
Thanks.  Still a LOT more to do.  Need to work on tutorial next

**Comment by avinabadasgupta** [comment]
> Thanks. Still a LOT more to do. Need to work on tutorial next
> […](#)

Really looks awesome! Passed all checks. Merge it in?

**Pull request merged**
