### PR TITLE
Add rvalue version of push API

### PR DESCRIPTION
**Pull request by avinabadasgupta**

### CODE REVIEW

**Comment by klingaard** [comment]
You know I'm gonna ask this -- can you add this to the other resources as well?

**Comment by klingaard** [comment]
I tested this with software we're building at SiFive and it works!

**Comment by avinabadasgupta** [comment]
> I tested this with software we're building at SiFive and it works!

**Comment by avinabadasgupta** [comment]
> I tested this with software we're building at SiFive and it works!

Great. I will do the same for other resources.

**Pull request merged**
