### PR TITLE
Fixing yaml-cpp version string; HDF5 for SimDB; compiler error with python glue

### LINKED ISSUE #308: YAML-CPP 0.7 not supported
yaml-cpp 0.7 has been released, but Sparta expects 0.6 (and does not die when it can't find it).  Need to 

1. Find and accept 0.7 
2. Check _FOUND variable and die

### PR DESCRIPTION
**Pull request by knute-sifive**
Sneaking in a compiler error fix to some python code

closes #308

### CODE REVIEW

**Review by benoy-sifive — COMMENTED** [review]
Did you mean to include the PythonInterpreter.cpp changes in this PR?  Seems unrelated

**Comment by klingaard** [comment]
Yes.  It’s harmless and has been sitting around in my work dir for a while.  We don’t use it nor compile it.

**Review by benoy-sifive — APPROVED** [review]

**Comment by knute-sifive** [comment]
Travis CI keeps timing out on me, but the regression passes.  Need to look into a different CI.

**Comment by timsnyder** [comment]
>Travis CI keeps timing out on me, but the regression passes. Need to look into a different CI.

@knute-sifive did you get this figured out?  I'm looking at some ci stuff for something else and could rework the map CI to use one of the other providers.

**Comment by knute-sifive** [comment]
I didn't but Jack did make some effort on PR #310 .  We're getting frustrated with these systems -- either we're nothing using them correctly or ... 🤷🏻‍♂️

**Pull request merged**
