### PR TITLE
Fix duplicate Argos transaction bug

### PR DESCRIPTION
**Pull request by bdutro**
Changes Collector to write last value instead of current value when closing a record.

This might need additional changes in `writeRecord_()` to be 100% correct because I don't totally understand the interface, but this seems to fix an issue we've been seeing with duplicate records.

### CODE REVIEW

**Comment by bdutro** [comment]
Looks like the Travis CI job was killed because it exceeded the runtime limit.

**Comment by nilanjan** [comment]
This is out of context question!

Sorry to reach out to the group like this. I was trying to use MAP for a project and had several questions. Was wondering if you have any QA group communication channel for discussing about how to use MAP and etc.?

Again sorry for contacting like this.

**Comment by knute-sifive** [comment]
> This is out of context question!
> 
> Sorry to reach out to the group like this. I was trying to use MAP for a project and had several questions. Was wondering if you have any QA group communication channel for discussing about how to use MAP and etc.?
> 
> Again sorry for contacting like this.

Definitely out of context.  :laughing: 

No, we haven't set up discussion groups or a QA channel yet.  On my list of things to do.  If you have a recommendation, I'm all ears.

For now, file an issue against MAP and I'll do my best to answer them.

**Comment by jackjchen** [comment]
> No, we haven't set up discussion groups or a QA channel yet. On my list of things to do. If you have a recommendation, I'm all ears.

A couple of choices would be a public slack workspace with available integrations to github if you like: https://github.com/integrations/slack or https://gitter.im/ may have similar integration.

**Comment by nilanjan** [comment]
@jackjchen @knute-sifive I think its a good idea to have a slack QA channel; people like me who are using this will be greatly benefitted by your expert advise and contribute to the repo. Also https://slack.github.com/ slack+github collaboration works good too.

**Comment by nilanjan** [comment]
Please let me know when you open the channel. I might need some quick help. Most of the global variables _GBL_* are hitting access error after setting it in singleton class or in any other class in MacOS (c++17 clang version 10.0.0 
). 
KeyValue.hpp:351 -> KeyValue::GBL_type_name_map[typeid(type).name()] = boost::trim_left_copy(*current_type_); 
StringManager.hpp:227 ->  sparta_assert(_GBL_string_manager && _GBL_string_manager->is_constructed == IS_CONSTRUCTED_CONST,"Attempted to access StringManager singleton before it was statically constructed."); -> this fires [ solved by using a setter method in the StringManager class]

**Comment by knute-sifive** [comment]
> Please let me know when you open the channel. I might need some quick help. Most of the global variables _GBL_* are hitting access error after setting it in singleton class or in any other class in MacOS (c++17 clang version 10.0.0
> ).
> KeyValue.hpp:351 -> KeyValue::GBL_type_name_map[typeid(type).name()] = boost::trim_left_copy(*current_type_);
> StringManager.hpp:227 -> sparta_assert(_GBL_string_manager && _GBL_string_manager->is_constructed == IS_CONSTRUCTED_CONST,"Attempted to access StringManager singleton before it was statically constructed."); -> this fires [ solved by using a setter method in the StringManager class]

Nilanjan, please go ahead and open a GitHub issue for this and I'll address it there.  I'm pretty Brett doesn't want anymore emails about this.  :laughing:

**Comment by davidsifive** [comment]
@bdutro-sv, thanks for fixing this!

**Pull request merged**
