### PR TITLE
bumping cmake version to 3.19, needed to ensure HDF5::HDF5 target exists

### LINKED ISSUE #407: WeightedContextCounter: move from examples to sparta proper
Counter is defined in ```test/ContextCounter/WeightedContextCounter.hpp```

But it's used by https://github.com/riscv-software-src/riscv-perf-model (in ```Dispatch.cpp```) so it should probably be part of sparta proper instead of an example and test.

### PR DESCRIPTION
**Pull request by peter-d**
Fixes #407

### CODE REVIEW

**Comment by knute-sifive** [comment]
Did you mean to say it fixes #407 ?

**Comment by knute-sifive** [comment]
I don't see issue with this -- we're using cmake 3.25 in house. Let me do a little testing just to make sure and I'll merge it in!  Thanks!

**Review by knute-sifive — APPROVED** [review]
LGTM

**Comment by peter-d** [comment]
Just to double check: what's the policy here? Am I allowed to merge myself once approved?

**Comment by knute-sifive** [comment]
> Just to double check: what's the policy here? Am I allowed to merge myself once approved?

Yep.  If I've given that power, you are free to use it.  😁

**Pull request merged**
