### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**

### CODE REVIEW

**Comment by klingaard** [comment]
Curious, before I merge this change -- got any others to bundle with it?

**Comment by h0lyalg0rithm** [comment]
@klingaard No I think this is it,Didnt come across any more

**Comment by jackjchen** [comment]
Could remove a character from "withing"->"within": https://github.com/sparcians/map/blob/bd3a6dfb649468e3e3bd13a2edec69baec916fa1/sparta/README.md?plain=1#L87

**Comment by h0lyalg0rithm** [comment]
@jackjchen updated thanks

**Pull request merged**
