### PR TITLE
Fixed issue with Queue entry allocation and deallocation

### PR DESCRIPTION
**Pull request by davidsifive**
The Queue allocates memory using 'nextPowerOfTwo_(num_entries*2)'. For example,
if 5 entries are requested, storage is allocated for 16 entries. The queue was
not managing the construction/destruction of the Queue entries properly allowing
all 16 entries to concurrently be valid, constructed objects even though the
user only request 5.  Fixed this by using a placement new when pushing an entry
and by explicitly calling the destructor when invalidating an entry.

### CODE REVIEW

**Comment by klingaard** [comment]
Hey Avi, can you take a peek at this?

**Comment by avinabadasgupta** [comment]
Looks good to me.

**Comment by klingaard** [comment]
I think this is causing a memory leak in the CoreExample.  Investigating...

**Comment by klingaard** [comment]
Yep.  If I revert this, the CoreExample runs to completion.  With this change, the CoreExample runs out of memory.  I think the in place new is bypassing the allocator somehow.

**Pull request merged**
