### PR TITLE
Add plato viz tool to repo per issue #111

### PR DESCRIPTION
**Pull request by MichaelSchoenfelder-SiV**
Helios was renamed back to Plato; we'll use "Helios" as the name of the suite of tools.
Fixed the logout issue.
Demonstrated use of conda to package pre-requisites.
Removed unneeded packages.
Added comments to dead-but-maybe-useful code
Updated README.md with simpler instructions and helper scripts.

### CODE REVIEW

**Comment by klingaard** [comment]
The "failed" runs appear to be some issue with a bash upload issue, but this is awesome!

**Comment by MichaelSchoenfelder-SiV** [comment]
The plato component does not need a build.  There are some tests on the widgets, but there was no infrastructure to run them.  The bash error is related to the conda recipes for sparta and seems to happen intermittently.

`Starting: Upload package
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/runners/2.166.3/work/_temp/3a01af46-fa45-40bf-afbb-e139f284be48.sh
Usage: upload_package [OPTIONS] FEEDSTOCK_NAME FEEDSTOCK_ROOT RECIPE_ROOT
                      CONFIG_FILE
Try 'upload_package --help' for help.

Error: Invalid value for 'RECIPE_ROOT': Directory './.ci_support/osx_python3.7.____cpython.yaml' is a file.

##[error]Bash exited with code '2'.
Finishing: Upload package
`

**Comment by timsnyder** [comment]
Hopefully the commits I pushed will make the CI pass for this.

**Comment by klingaard** [comment]
Looks good!

**Pull request merged**
